# Docker Compose untuk pengembangan lokal
version: '3.8'

services:
  # Database PostgreSQL
  postgres:
    image: postgres:15
    container_name: gcb-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: greencyclebank
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API (NestJS)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      target: development
    container_name: gcb-api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/greencyclebank
      - PORT=3001
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

  # Frontend (Next.js)
  web:
    build:
      context: .
      dockerfile: ./apps/mobile/Dockerfile
      target: development
    container_name: gcb-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  postgres-data:
  node_modules:
